[project]
name = "capstone-project-26t1-3900-w18a-date"
created = "2026-04-05T21:59:17.421666"
framework_version = "0.8.9"
secrets = ".env"

[cli]
version = "1.0.0"
command = "co init"
template = "none"

[agent]
algorithm = "ed25519"
default_model = "co/gemini-2.5-pro"
max_iterations = 10
created_at = "2026-03-25T08:26:37.479945"
